export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const TOGGLE_BUTTON = "TOGGLE_BUTTON";
export const CHANGE_ACTION = "CHANGE_ACTION";