export const ADD_PRODUCT = "ADD_PRODUCT";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const TOGGLE_BUTTON = "TOGGLE_BUTTON";
export const CHANGE_ACTION = "CHANGE_ACTION";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_FORM_TOGGLE = "ADD_PRODUCT_FORM_TOGGLE";